### ISSUE TITLE
Diseño: Modelado UML

### ISSUE THREAD

**Issue by navicor90** [lightning-round/debtrack#1]
Herramientas:
* PlantUML
* ArgoUML
* BoUML
* Umbrello
* Enterprise Architect

Elección:
[PlantUML](http://plantuml.sourceforge.net/)

**Comment by coco19** [comment]
Definitivamente [plantuml!!!](http://www.planttext.com/)

**Comment by coco19** [comment]
Si la herramienta ya fue elegida, notendrías que cerrar el issue @navicor90
